POSTGRESQL_DATABASE_NAME: agentapp
POSTGRESQL_HOST: 34.100.227.8
POSTGRESQL_PORT: 5432
POSTGRESQL_USERNAME: agentapp
POSTGRESQL_PASSWORD: qazxc1234
POSTGRESQL_CONNECTION_MAX_IDLE_TIME: 120

REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379

PORT: 8080

JWT_SECRET: "f2541a15-2a94-446f-978f-b1288e05"